### ISSUE TITLE
App size increased with nearly 20mb

### ISSUE THREAD

**Issue by PatrickKuijpers** [DonkeyRepublic/lockkit-android#2]
After adding the lockkit SDK, our app's apk increased with 19.5mb!
I can't imaging that this can't be reduced.

Please decrease the size of the SDK.
(we're using version 1.1.2)

**Comment by Nonda95** [comment]
We made a migration from realm (which was responsible for big app size) to sqldelight. To give a possibility to migrate users and saved Ekeys, the migration is divided into two releases — 1.2.0 and 1.3.0. 1.2.0 creates a new sqldelight database and moves all the data from realm + saves all new data to sqldelight, so realm dependency is still there. 1.3.0 release no longer depends on realm which should decrease app size significantly — our sample app has ~20 MB apk size for 1.2.0 and ~8 MB apk size for 1.3.0-SNAPSHOT. The stable 1.3.0 release should be available tomorrow
